---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: mrrobot-custom-fedora-sway
description: Personal OS image - standard
base-image: ghcr.io/wayblueorg/sway
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: script
    scripts:
      - install-netbird.sh
  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      copr:
        - atim/starship
        - scottames/ghostty
    install:
      packages:
        - terra-release
        - zed
        - micro
        - starship
        - ghostty
        - neovim
        - git
        - wireguard-tools
        - podman
        - yubikey-manager
        - gnupg2-scdaemon
        - libatomic
        - pcsc-lite
        - pcsc-lite-ccid
        - pam-u2f
        - libfido2
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - opensc
        - opensc-libs
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - md.obsidian.Obsidian
          - com.brave.Browser
          - io.github.ArmandAgopian.zen-browser
          - com.bitwarden.desktop
          - com.protonvpn.www
      - scope: user
  - type: signing
